### ISSUE TITLE
Set target_size = 320 and get bad results

### ISSUE THREAD

**Issue by Realjayden** [Qengineering/YoloV10-ncnn-Raspberry-Pi-4#1]
![output](https://github.com/Qengineering/YoloV10-ncnn-Raspberry-Pi-4/assets/89341955/869bec4b-9b54-4efa-b735-eca9e29ffcbb)
![4e0ef1986e23eb42cdea8cdff96cfd8](https://github.com/Qengineering/YoloV10-ncnn-Raspberry-Pi-4/assets/89341955/e2349433-6346-427a-996f-6eaf82755cc9)

I just modify the target_size, and get this result. Could someone tell me why?

**Comment by Qengineering** [comment]
https://github.com/Qengineering/YoloV10-ncnn-Raspberry-Pi-4/tree/main#opset

**Comment by Realjayden** [comment]
> https://github.com/Qengineering/YoloV10-ncnn-Raspberry-Pi-4/tree/main#opset

Thank you for your answer.
