### ISSUE TITLE
Issue running Cmake

### ISSUE THREAD

**Issue by tuvovan** [Qengineering/YoloV10-ncnn-Raspberry-Pi-4#2]
Hi I'm trying to compile using Cmake. I got the following error:

`make[2]: *** No rule to make target '/usr/local/lib/ncnn/libncnn.a', needed by '/home/pi/code/MyDir/YoloV10'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object CMakeFiles/YoloV10.dir/yolov10.cpp.o
/home/pi/code/MyDir/yolov10.cpp:1:10: fatal error: layer.h: No such file or directory
    1 | #include "layer.h"
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/YoloV10.dir/build.make:76: CMakeFiles/YoloV10.dir/yolov10.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: C`

Can you please let me know what is the issue here?

**Comment by Qengineering** [comment]
Did you [install ncnn](https://qengineering.eu/install-ncnn-on-raspberry-pi-4.html) on your RPi?

**Comment by tuvovan** [comment]
thanks! it works now!
